/* In Russia, in 2026, some idiotic blocking of libraries and repositories began:
 1. For a new build of the project, comment out line "# org.gradle.offline=true"
 in file "gradle.properties" to download the Gradle cache;
 In Russia, you may need a VPN for this;
 2. Build this project command "./gradlew build" or by running a task;
 3. Then uncomment the line again and rebuild the project to run in semi-local mode;
 */

import java.time.LocalDateTime

// DEV resources path
buildscript {
    repositories {
        mavenLocal()
        mavenCentral()
        maven {
            name = 'MinecraftForge'
            url = 'https://maven.minecraftforge.net/'
        }
        maven {
            name = 'SpongePowered'
            url = 'https://repo.spongepowered.org/repository/maven-public/'
        }
    }
    dependencies {
        classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '4.1.14'
        classpath group: 'org.spongepowered', name: 'mixingradle', version: '0.7.38'
    }
}

// Plugins for creating JAR
apply plugin: 'eclipse'
apply plugin: 'idea'
apply plugin: 'net.minecraftforge.gradle'
apply plugin: 'org.spongepowered.mixin'

// JAR naming
version = getCustomVersion()
group = mod_group_id
archivesBaseName = "${mod_name} ${minecraft_version} Unofficial"

// Snapshot version
def getCustomVersion() {
    Date date = new Date()
    String month = LocalDateTime.now().month.toString().substring(0, 3)
    return "v.${mod_version}-" + date.format("dd") + month.charAt(0) + month.substring(1).toLowerCase() + date.format("yyyy") + '-Snapshot'
}

// Set Java compatibility to version
java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

// launch in DEV environment
minecraft {
    mappings channel: project.mapping_channel.toString(), version: project.mapping_version.toString()
    accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')

    runs {
        configureEach {
            properties 'mixin.env.remapRefMap': 'true'
            property 'mixin.env.refMapRemappingFile',
                    "${project.projectDir}/build/createSrgToMcp/output.srg".toString()
            property "mixin.debug", 'true'
            property "mixin.debug.verify", 'false'
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            property 'fml.coreMods.load',
                    "${mod_group_id}.mixin.NpcMixinCore".toString()
        }
        client {
            workingDirectory project.file('run/client')
            args "--username=BetaZavr${new Random().nextInt(10)}".toString(),
                    '--tweakClass',
                    'org.spongepowered.asm.launch.MixinTweaker',
                    '--mixin',
                    "mixins.${mod_id}.json".toString()
        }
        server {
            workingDirectory project.file('run/server')
            args '--tweakClass',
                    'org.spongepowered.asm.launch.MixinTweaker',
                    '--mixin',
                    "mixins.${mod_id}.json".toString()
                    //, 'nogui'
        }
    }
}

// Add Maven repositories
repositories {
    mavenLocal()
    mavenCentral()
}

// Project dependencies (required libraries)
dependencies {
    // Minecraft Forge
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"

    // Mixin Lib
    implementation('org.spongepowered:mixin:0.8.5') {
        exclude module: 'guava'
        exclude module: 'commons-io'
        exclude module: 'gson'
    }
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'

}

// Resource processing (mcmod.info file)
processResources {
    inputs.property 'version', project.version
    inputs.property 'mcversion', minecraft_version
    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
        expand  'mod_id'            : mod_id,
                'mod_name'          : mod_name,
                'mod_version'       : mod_version,
                'minecraft_version' : minecraft_version,
                'mod_description'   : mod_description,
                'mod_credits'       : mod_credits,
                'mod_authors'       : mod_authors.replace(", ", "\", \""),
                'mod_logo_file'     : mod_logo_file,
                'mod_url'           : mod_url,
                'mod_update_url'    : mod_update_url
    }
}

// JAR file manifest settings
mixin {
    add sourceSets.main, "mixins.${mod_id}.refmap.json"
    config "mixins.${mod_id}.json"
}

// Creating a JAR file
jar {
    // Manifest settings
    manifest {
        attributes([
                "Implementation-Title"       : mod_name,
                "Implementation-Version"     : mod_version,
                "Implementation-Vendor"      : mod_authors,
                "Implementation-Timestamp"   : new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                "FMLCorePluginContainsFMLMod": "true",
                "FMLCorePlugin"              : "${mod_group_id}.mixin.NpcMixinCore".toString(),
                "FMLAT"                      : "deobfuscation.cfg",
                "TweakClass"                 : "org.spongepowered.asm.launch.MixinTweaker",
                "MixinConfigs"               : "mixins.${mod_id}.json".toString(),
                "ForceLoadAsMod"             : "true",
                "CertificateFingerprint"     : project.findProperty('certificateFingerprint') ?: "",
        ])
    }
    // Reobfuscate field and method names
    finalizedBy('reobfJar')
}

// The content below is needed for IntelliJ IDEA to be able to see the mod's resources
idea {
    module {
        inheritOutputDirs = true
        downloadJavadoc = true
        downloadSources = true
    }
}

tasks.register('prepareAssets', Copy) {
    group = 'build'
    from project.file('src/main/resources')
    into project.file('build/classes/java/main')
}

classes.dependsOn(prepareAssets)
