org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G
org.gradle.daemon=false
org.gradle.offline=true

minecraft_version=1.12.2
minecraft_version_range=[1.12.2, 1.12)
forge_version=14.23.5.2860
forge_version_range=[14.23,)
loader_version_range=[14.23,)
mapping_channel=snapshot
mapping_version=20171003-1.12

# Noppes Mod change started June 2018
# 1: simple change of mod code by Noppes
# 2: cancel reset of class fields privacy, switch to reflection
# 3: cancel reflection, switch to mixins
# 4: mixins and reflections combination
# 5: packages and GUIs have been rewritten
# number of released builds of the mod is indicated next
mod_version=5.433
mod_id=customnpcs
mod_name=Custom NPCs
mod_license=All Rights Reserved
mod_group_id=noppes.npcs
mod_credits=A lot of people, see the list at the forum
mod_authors=Noppes, Goodbird, BetaZavr
mod_description=forge.mod.customnpcs.description
mod_logo_file=/logo_unofficial.png
mod_url=http://www.kodevelopment.nl/minecraft/customnpcs/
mod_update_url=
