org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.3.12
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_version=1.016
mod_id=customnpcs
mod_name=Custom NPCs
mod_license=All Rights Reserved
mod_group_id=noppes.npcs
mod_credits=A lot of people, see the list at the forum
mod_authors=Noppes, Goodbird, BetaZavr
mod_description=Custom Npcs mod lets you create your own npcs and lets you customize them how you want
