package noppes.npcs.constants;

public enum EnumScriptType {

   INIT("init"),
   TICK("tick"),
   INTERACT("interact"),
   DIALOG("dialog"),
   DAMAGED("damaged"),
   DIED("died"),
   ATTACK_MELEE("meleeAttack"),
   TARGET("target"),
   COLLIDE("collide"),
   KILL("kill"),
   DIALOG_OPTION("dialogOption"),
   TARGET_LOST("targetLost"),
   ROLE("role"),
   RANGED_LAUNCHED("rangedLaunched"),
   CLICKED("clicked"),
   FALLEN_UPON("fallenUpon"),
   RAIN_FILLED("rainFilled"),
   BROKEN("broken"),
   HARVESTED("harvested"),
   EXPLODED("exploded"),
   NEIGHBOR_CHANGED("neighborChanged"),
   REDSTONE("redstone"),
   DOOR_TOGGLE("doorToggle"),
   TIMER("timer"),
   TOSS("toss"),
   CONTAINER_OPEN("containerOpen"),
   CONTAINER_CLOSED("containerClosed"),
   LOGIN("login"),
   LOGOUT("logout"),
   CHAT("chat"),
   DAMAGED_ENTITY("damagedEntity"),
   DIALOG_CLOSE("dialogClose"),
   SPAWN("spawn"),
   TOSSED("tossed"),
   PICKEDUP("pickedUp"),
   PICKUP("pickUp"),
   ATTACK("attack"),
   PROJECTILE_TICK("projectileTick"),
   PROJECTILE_IMPACT("projectileImpact"),
   FACTION_UPDATE("factionUpdate"),
   LEVEL_UP("levelUp"),
   QUEST_START("questStart"),
   QUEST_COMPLETED("questCompleted"),
   QUEST_TURNING("questTurnIn"),
   KEY_PRESSED("keyPressed"),
   KEY_RELEASED("keyReleased"),
   SCRIPT_TRIGGER("trigger"),
   PLAY_SOUND("playSound"),
   STOP_SOUND("stopSound"),
   CUSTOM_GUI_CLOSED("customGuiClosed"),
   CUSTOM_GUI_BUTTON("customGuiButton"),
   CUSTOM_GUI_SLOT("customGuiSlot"),
   CUSTOM_GUI_SCROLL("customGuiScroll"),
   CUSTOM_GUI_SLOT_CLICKED("customGuiSlotClicked"),

   // New from Unofficial (BetaZavr)
   MOUSE_PRESSED("mousePressed"),
   MOUSE_RELEASED("mouseReleased"),
   MOUSE_SCROLLED("mouseScrolled"),
   MOUSE_MOVE("mouseMove"),
   GUI_OPEN("openGUI"),
   ITEM_FISHED("itemFished"),
   ITEM_CRAFTED("itemCrafted"),
   QUEST_LOG_BUTTON("questButton"),
   QUEST_CANCELED("questCanceled"),
   SOUND_TICK_EVENT("soundTickEvent"),
   NEED_BLOCK_DAMAGED("needBlockDamage"),
   KEY_GUI_UP("keyGUIPressed"),
   PLEASED("plased"),
   CUSTOM_TELEPORT("customTeleport"),
   KEY_ACTIVE("keyActive"),
   ANIMATION_PLAY("customAnimationPlay"),
   ANIMATION_STOP("customAnimationStop"),
   ANIMATION_TICK("customAnimationTick"),
   ANIMATION_NEXT_FRAME("customAnimationNextFrame"),
   IN_GAME("inGame"),
   SEND_COMMAND("sendCommand"),
   REGION_ENTER("regionEnter"),
   REGION_LEAVE("regionLeave"),
   GUI_SLOT_CHANGED("slotChanged"),
   // Potion
   POTION_IS_READY("isReady"),
   POTION_PERFORM("performEffect"),
   POTION_AFFECT("affectEntity"),
   POTION_END("endEffect"),
   SCRIPT_COMMAND("scriptCommand"),
   PACKAGE_RECEIVED("packageReceived"),
   PACKAGE_FROM("packageFrom");

   public static final EnumScriptType[] npcScripts = new EnumScriptType[]{ INIT, TICK, INTERACT, DIALOG, DIALOG_OPTION, DIALOG_CLOSE,
           SCRIPT_TRIGGER, DAMAGED, DIED, ATTACK_MELEE, RANGED_LAUNCHED, TARGET, TARGET_LOST, KILL, ROLE, COLLIDE, TIMER, PROJECTILE_TICK,
           PROJECTILE_IMPACT, CUSTOM_GUI_SCROLL, CUSTOM_GUI_SLOT, CUSTOM_GUI_CLOSED, CUSTOM_GUI_BUTTON, CUSTOM_GUI_SLOT_CLICKED,
           NEED_BLOCK_DAMAGED, CUSTOM_TELEPORT, ANIMATION_PLAY, ANIMATION_STOP, ANIMATION_TICK, ANIMATION_NEXT_FRAME };
   public static final EnumScriptType[] blockScripts = new EnumScriptType[]{ INIT, TICK, INTERACT, REDSTONE, FALLEN_UPON, BROKEN,
           SCRIPT_TRIGGER, EXPLODED, RAIN_FILLED, NEIGHBOR_CHANGED, CLICKED, HARVESTED, COLLIDE, TIMER, CUSTOM_GUI_SCROLL, CUSTOM_GUI_SLOT,
           CUSTOM_GUI_CLOSED, CUSTOM_GUI_BUTTON, CUSTOM_GUI_SLOT_CLICKED };
   public static final EnumScriptType[] doorScripts = new EnumScriptType[]{ INIT, TICK, INTERACT, REDSTONE, FALLEN_UPON, BROKEN,
           SCRIPT_TRIGGER, EXPLODED, RAIN_FILLED, NEIGHBOR_CHANGED, CLICKED, HARVESTED, COLLIDE, TIMER, DOOR_TOGGLE, CUSTOM_GUI_SCROLL,
           CUSTOM_GUI_SLOT, CUSTOM_GUI_CLOSED, CUSTOM_GUI_BUTTON, CUSTOM_GUI_SLOT_CLICKED };
   public static final EnumScriptType[] playerScripts = new EnumScriptType[]{ INIT, TICK, INTERACT, BROKEN, PICKUP, CONTAINER_OPEN,
           CONTAINER_CLOSED, DAMAGED, DIED, ATTACK, KILL, DAMAGED_ENTITY, RANGED_LAUNCHED, TIMER, LOGIN, LOGOUT, CHAT, FACTION_UPDATE,
           TOSS, DIALOG, DIALOG_OPTION, DIALOG_CLOSE, QUEST_START, QUEST_COMPLETED, QUEST_TURNING, SCRIPT_TRIGGER, KEY_PRESSED, KEY_RELEASED,
           PROJECTILE_TICK, PROJECTILE_IMPACT, PLAY_SOUND, CUSTOM_GUI_SCROLL, CUSTOM_GUI_SLOT, CUSTOM_GUI_CLOSED, CUSTOM_GUI_BUTTON,
           CUSTOM_GUI_SLOT_CLICKED, GUI_OPEN, ITEM_FISHED, ITEM_CRAFTED, QUEST_LOG_BUTTON, QUEST_CANCELED, PACKAGE_FROM, PACKAGE_RECEIVED,
           KEY_GUI_UP, MOUSE_MOVE, PLEASED, CUSTOM_TELEPORT, KEY_ACTIVE, IN_GAME, SEND_COMMAND, MOUSE_PRESSED, MOUSE_RELEASED, MOUSE_SCROLLED,
           SCRIPT_COMMAND, REGION_ENTER, REGION_LEAVE, ANIMATION_PLAY, ANIMATION_STOP, ANIMATION_TICK, ANIMATION_NEXT_FRAME, GUI_SLOT_CHANGED};
   public static final EnumScriptType[] itemScripts = new EnumScriptType[]{ INIT, TICK, INTERACT, ATTACK, TOSSED, SPAWN, PICKEDUP,
           CUSTOM_GUI_SCROLL, CUSTOM_GUI_SLOT, CUSTOM_GUI_CLOSED, CUSTOM_GUI_BUTTON, CUSTOM_GUI_SLOT_CLICKED };
   // New from Unofficial (BetaZavr)
   public static final EnumScriptType[] potionScripts = new EnumScriptType[]{ INIT, SCRIPT_TRIGGER, POTION_IS_READY, POTION_PERFORM,
           POTION_AFFECT, POTION_END };
   public static final EnumScriptType[] clientScripts = new EnumScriptType[]{ SOUND_TICK_EVENT };

   public final String function;

   EnumScriptType(String functionHook) { function = functionHook; }

}
